panjang = input (" Masukan Variable Panjang")
lebar = input ("Masukan Variable Lebar")
KelilingSegiempat = 2*int(panjang)+2*int(lebar)
LuasSegiempat = int(panjang)*int(lebar)
print("Panjang Segiempat =", panjang)
print("Lebar Segiempat =", lebar)
print("Keliling Segiempat =", KelilingSegiempat)
print("Luas Segiempat =", LuasSegiempat)